// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace NotelyCore.Persistence.Migrations
{
    [DbContext(typeof(NotelyCoreDbContext))]
    [Migration("20190719151643_PriorityEnumConversion")]
    partial class PriorityEnumConversion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NotelyCore.Domain.Note", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("Priority")
                        .IsRequired();

                    b.Property<string>("Subject");

                    b.HasKey("NoteId");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            NoteId = 1,
                            Body = "Body 1",
                            CreatedOn = new DateTime(2019, 7, 19, 18, 16, 43, 627, DateTimeKind.Local).AddTicks(3790),
                            Priority = "Critical",
                            Subject = "Note 1"
                        },
                        new
                        {
                            NoteId = 2,
                            Body = "Body 2",
                            CreatedOn = new DateTime(2019, 7, 19, 18, 16, 43, 628, DateTimeKind.Local).AddTicks(3117),
                            Priority = "Neutral",
                            Subject = "Note 2"
                        },
                        new
                        {
                            NoteId = 3,
                            Body = "Body 3",
                            CreatedOn = new DateTime(2019, 7, 19, 18, 16, 43, 628, DateTimeKind.Local).AddTicks(3128),
                            Priority = "Low",
                            Subject = "Note 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
